# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataobject.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataobject.proto',
  package='pb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x61taobject.proto\x12\x02pb\",\n\x0e\x63omplexFloat32\x12\x0c\n\x04real\x18\x01 \x01(\x02\x12\x0c\n\x04imag\x18\x02 \x01(\x02\"(\n\x08rangeI32\x12\r\n\x05lower\x18\x01 \x01(\x05\x12\r\n\x05upper\x18\x02 \x01(\x05\"\xc3\x03\n\x0bSpaceObject\x12\x19\n\x03mix\x18\x01 \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1a\n\x04\x65\x63ho\x18\x02 \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1e\n\x08location\x18\x03 \x03(\x0b\x32\x0c.pb.rangeI32\x12\x19\n\x03row\x18\x04 \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1d\n\x07\x64ynamic\x18\x05 \x03(\x0b\x32\x0c.pb.rangeI32\x12!\n\x0bmeasurement\x18\x06 \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1b\n\x05phase\x18\x07 \x03(\x0b\x32\x0c.pb.rangeI32\x12&\n\x10\x65xtra_attr_value\x18\x08 \x03(\x0b\x32\x0c.pb.rangeI32\x12\x17\n\x01x\x18\t \x03(\x0b\x32\x0c.pb.rangeI32\x12\x17\n\x01y\x18\n \x03(\x0b\x32\x0c.pb.rangeI32\x12\x17\n\x01z\x18\x0b \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1d\n\x07\x63hannel\x18\x0c \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1a\n\x04grad\x18\r \x03(\x0b\x32\x0c.pb.rangeI32\x12\x18\n\x02rf\x18\x0e \x03(\x0b\x32\x0c.pb.rangeI32\x12\x1b\n\x05\x62lade\x18\x0f \x03(\x0b\x32\x0c.pb.rangeI32\"\xc9\x02\n\nDataObject\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.pb.complexFloat32\x12\r\n\x05image\x18\x06 \x03(\x05\x12\x10\n\x08size_dim\x18\x02 \x03(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\r\n\x05order\x18\x04 \x01(\x05\x12\x1e\n\x05space\x18\x05 \x03(\x0b\x32\x0f.pb.SpaceObject\x12\x17\n\x0fslice_thickness\x18~ \x01(\x02\x12\x1e\n\x16spacing_between_slices\x18\x7f \x01(\x02\x12\x14\n\x0bvoxel_sizes\x18\x80\x01 \x03(\x02\x12$\n\x1bloc_ap_rl_fh_row_image_oris\x18\x81\x01 \x03(\x02\x12$\n\x1bloc_ap_rl_fh_col_image_oris\x18\x82\x01 \x03(\x02\x12 \n\x17loc_ap_rl_fh_offcentres\x18\x83\x01 \x03(\x02')
)




_COMPLEXFLOAT32 = _descriptor.Descriptor(
  name='complexFloat32',
  full_name='pb.complexFloat32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='pb.complexFloat32.real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imag', full_name='pb.complexFloat32.imag', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_RANGEI32 = _descriptor.Descriptor(
  name='rangeI32',
  full_name='pb.rangeI32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='pb.rangeI32.lower', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper', full_name='pb.rangeI32.upper', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=110,
)


_SPACEOBJECT = _descriptor.Descriptor(
  name='SpaceObject',
  full_name='pb.SpaceObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mix', full_name='pb.SpaceObject.mix', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='echo', full_name='pb.SpaceObject.echo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='pb.SpaceObject.location', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row', full_name='pb.SpaceObject.row', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic', full_name='pb.SpaceObject.dynamic', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement', full_name='pb.SpaceObject.measurement', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phase', full_name='pb.SpaceObject.phase', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_attr_value', full_name='pb.SpaceObject.extra_attr_value', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='pb.SpaceObject.x', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='pb.SpaceObject.y', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='pb.SpaceObject.z', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='pb.SpaceObject.channel', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grad', full_name='pb.SpaceObject.grad', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rf', full_name='pb.SpaceObject.rf', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blade', full_name='pb.SpaceObject.blade', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=564,
)


_DATAOBJECT = _descriptor.Descriptor(
  name='DataObject',
  full_name='pb.DataObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.DataObject.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='pb.DataObject.image', index=1,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size_dim', full_name='pb.DataObject.size_dim', index=2,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='pb.DataObject.size', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='pb.DataObject.order', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='space', full_name='pb.DataObject.space', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slice_thickness', full_name='pb.DataObject.slice_thickness', index=6,
      number=126, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spacing_between_slices', full_name='pb.DataObject.spacing_between_slices', index=7,
      number=127, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voxel_sizes', full_name='pb.DataObject.voxel_sizes', index=8,
      number=128, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc_ap_rl_fh_row_image_oris', full_name='pb.DataObject.loc_ap_rl_fh_row_image_oris', index=9,
      number=129, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc_ap_rl_fh_col_image_oris', full_name='pb.DataObject.loc_ap_rl_fh_col_image_oris', index=10,
      number=130, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc_ap_rl_fh_offcentres', full_name='pb.DataObject.loc_ap_rl_fh_offcentres', index=11,
      number=131, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=896,
)

_SPACEOBJECT.fields_by_name['mix'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['echo'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['location'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['row'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['dynamic'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['measurement'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['phase'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['extra_attr_value'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['x'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['y'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['z'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['channel'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['grad'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['rf'].message_type = _RANGEI32
_SPACEOBJECT.fields_by_name['blade'].message_type = _RANGEI32
_DATAOBJECT.fields_by_name['data'].message_type = _COMPLEXFLOAT32
_DATAOBJECT.fields_by_name['space'].message_type = _SPACEOBJECT
DESCRIPTOR.message_types_by_name['complexFloat32'] = _COMPLEXFLOAT32
DESCRIPTOR.message_types_by_name['rangeI32'] = _RANGEI32
DESCRIPTOR.message_types_by_name['SpaceObject'] = _SPACEOBJECT
DESCRIPTOR.message_types_by_name['DataObject'] = _DATAOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

complexFloat32 = _reflection.GeneratedProtocolMessageType('complexFloat32', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXFLOAT32,
  __module__ = 'dataobject_pb2'
  # @@protoc_insertion_point(class_scope:pb.complexFloat32)
  ))
_sym_db.RegisterMessage(complexFloat32)

rangeI32 = _reflection.GeneratedProtocolMessageType('rangeI32', (_message.Message,), dict(
  DESCRIPTOR = _RANGEI32,
  __module__ = 'dataobject_pb2'
  # @@protoc_insertion_point(class_scope:pb.rangeI32)
  ))
_sym_db.RegisterMessage(rangeI32)

SpaceObject = _reflection.GeneratedProtocolMessageType('SpaceObject', (_message.Message,), dict(
  DESCRIPTOR = _SPACEOBJECT,
  __module__ = 'dataobject_pb2'
  # @@protoc_insertion_point(class_scope:pb.SpaceObject)
  ))
_sym_db.RegisterMessage(SpaceObject)

DataObject = _reflection.GeneratedProtocolMessageType('DataObject', (_message.Message,), dict(
  DESCRIPTOR = _DATAOBJECT,
  __module__ = 'dataobject_pb2'
  # @@protoc_insertion_point(class_scope:pb.DataObject)
  ))
_sym_db.RegisterMessage(DataObject)


# @@protoc_insertion_point(module_scope)
